---
name: CI
on:
  push:
    branches: master
  pull_request:
    branches: master

permissions:
  contents: read

jobs:
  ci:
    name: continuous-integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        id: setup-python-step
        with:
          python-version-file: .python-version

      - name: Run tests
        shell: bash
        run: |
          just test
